export type ServiceCategory = {
  id: string;
  label: string;
  items: string[];
};

export const SERVICE_CATALOG: ServiceCategory[] = [
  {
    id: "ortodontia",
    label: "Aparelhos Ortodônticos / Ortopédicos",
    items: [
      "Confecção de Arco Lingual de Nance Fixo",
      "Confecção de Arco Lingual de Nance Removível",
      "Confecção de Aparelho Bi Helix",
      "Confecção de Aparelho Quadri Helix",
      "Confecção de Barra Transpalatina 3D",
      "Confecção de Aparelho Bionator de Balters",
      "Confecção de Botão de Nance",
      "Confecção de Botão de Nance Modificado",
      "Confecção de Disjuntor Palatino Haas ou Hirax Convencional",
      "Confecção de Disjuntor Palatino Haas ou Hirax Convencional c/ Gancho para Máscara",
      "Confecção de Disjuntor Palatino Haas ou Hirax Modificado p/ Dentição Mista ou Decídua",
      "Confecção de Disjuntor Palatino Haas ou Hirax Modificado p/ Dentição Mista ou Decídua c/ Gancho para Máscara",
      "Confecção de Disjuntor Palatino Hirax c/ Parafuso, Borboleta, Aranha",
      "Confecção de Disjuntor Palatino Hirax c/ Parafuso, Borboleta, Aranha c/ Gancho para Máscara",
      "Confecção de Placa Expansora",
      "Confecção de Placa Expansora com Botão Nasal",
      "Confecção de Plano Inclinado",
      "Confecção de Contenção Fixa Inferior Não Higiênica",
      "Confecção de Contenção Fixa Superior",
      "Confecção de Contenção Fixa Superior ou Inferior com Dente",
      "Confecção de Placa de Hawley",
      "Confecção de Placa de Contenção Removível com Dente",
      "Confecção de Aparelho de Frankel",
      "Confecção de Aparelho de Klammt",
      "Confecção de Aparelho Pendulum",
      "Aparelho T-Rex (Expansor + Pendex)",
      "Expansor Inferior de Negan",
      "Confecção de Placa Schwatz",
      "Confecção de Aparelho Ballester – Levantamento de Mordida Fixa",
      "Confecção de Aparelho Progênico",
      "Arco Palatino Fixo com Barra Palatina",
      "Confecção de Placa de Levantamento de Mordida Parcial",
      "Confecção de Placa de Levantamento de Mordida Total",
      "Confecção de Disjuntor Hirax com Grade",
      "Confecção de Disjuntor de McNamara",
      "Confecção de Placa de Acetato para Contenção 1 ou 1,5 mm",
      "Confecção de Placa de Contenção Arco Contínuo com Solda",
      "Confecção de Placa de Hawley com Grade",
      "Confecção de Splint Maxilar Thurow",
      "Confecção de Splint Maxilar com Grade Thurow",
      "Confecção de Expansor de Williams",
      "Confecção de Aparelho Planas",
      "Confecção de Aparelho Twin Block",
      "Ajustes em Peças Protéticas, Aparelhos Ortodônticos e Ortopédicos",
      "Repetição de Etapas Laboratoriais ou de Peças Protéticas, Aparelhos Ortodônticos e Ortopédicos",
    ],
  },
  {
    id: "pt",
    label: "PT - Prótese Total",
    items: [
      "Confecção de Moldeira Individual para Prótese Total Maxilar ou Mandibular",
      "Confecção da Placa Base em Resina Acrílica e Posicionamento em Plano de Cera para Prótese Total Maxilar ou Mandibular",
      "Montagem de Dentes para Prótese Total Maxilar ou Mandibular",
      "Acrilização, Acabamento e Polimento de Prótese Total Maxilar ou Mandibular",
      "Reembasamento em Prótese Total Maxilar ou Mandibular",
      "Confecção de Prótese Total Imediata Maxilar ou Mandibular",
      "Confecção de Prótese Total Temporária Maxilar ou Mandibular",
      "Ajustes em Peças Protéticas – Próteses Removíveis Total",
      "Repetição de Etapas Laboratoriais ou de Peças Protéticas – Próteses Removíveis Parcial ou Total",
    ],
  },
  {
    id: "ppr",
    label: "PPR - Prótese Parcial Removível",
    items: [
      "Confecção e Fundição de Grades Metálicas em Cromo Cobalto",
      "Confecção e Fundição de Grades Metálicas em Cromo Cobalto com Barra Platina",
      "Confecção e Fundição de Contra-Placa ou Levantamento em Metal, em Cromo Cobalto Maxilar",
      "Montagem de Dentes sobre Grade Maxilar ou Mandibular",
      "Encerramento, Escultura, Inclusão, Prensagem e Polimerização, Acabamento e Polimento de Resina e Dentes sobre Grade Metálica Maxilar ou Mandibular",
      "Ajustes em Peças Protéticas – Próteses Removíveis Parcial",
      "Repetição de Etapas Laboratoriais ou de Peças Protéticas – Próteses Removíveis Parcial",
    ],
  },
  {
    id: "fixa",
    label: "Prótese Fixa / Unitária",
    items: [
      "Fundição de Núcleo Metálico",
      "Confecção de Casquete em Metal sobre Núcleo",
      "Confecção de Casquete em Metal sobre Implante",
      "Aplicação, Alisamento, Polimento e Vitrificação de Porcelana no Casquete sobre Implante",
      "Aplicação, Alisamento, Polimento e Vitrificação de Cerâmica sobre Casquetes",
      "Confecção de Coroa Provisória em Resina",
      "Prótese Adesiva por Elemento",
      "Confecção de Ponte Fixa por Elemento",
      "Ajustes em Peças Protéticas – Prótese Fixa, Unitária e Ponte Fixa",
      "Repetição de Etapas Laboratoriais ou de Peças Protéticas – Prótese Fixa: Unitária e Ponte Fixa",
    ],
  },
  {
    id: "implantes",
    label: "Prótese sobre Implantes",
    items: [
      "Confecção de Barra Protocolo Maxilar",
      "Confecção de Barra Protocolo Mandibular",
      "Confecção de Solda em Barra Protocolo Mandibular",
      "Confecção de Solda em Barra Protocolo Maxilar",
      "Confecção de Guia Cirúrgica Maxilar",
      "Confecção de Guia Cirúrgica Mandibular",
      "Confecção de Próteses Protocolo Maxilar",
      "Confecção de Próteses Protocolo Mandibular",
      "Ajustes em Peças Protéticas – Prótese sobre Implantes",
      "Repetição de Etapas Laboratoriais ou de Peças Protéticas – Prótese sobre Implantes",
    ],
  },
  {
    id: "oclusais",
    label: "Placas Oclusais",
    items: [
      "Confecção de Placa Miorrelaxante em Resina Acrílica",
      "Confecção de Placa de Clareamento Maxilar",
      "Confecção de Placa de Clareamento Mandibular",
      "Ajustes em Peças Protéticas – Placas Oclusais",
      "Repetição de Etapas Laboratoriais ou de Peças Protéticas – Placas Oclusais",
    ],
  },
  {
    id: "modelos",
    label: "Modelos e Troqueis",
    items: [
      "Confecção de Modelo para Prótese Parcial e Total",
      "Confecção de Troquel Articulado Maxilar",
      "Confecção de Troquel Articulado Mandibular",
    ],
  },
  {
    id: "outros",
    label: "Outros Serviços",
    items: [
      "Acrilização de Prótese Parcial Removível Superior/Inferior",
      "Acrilização de Prótese Total Superior/Inferior",
      "Aparelho Ortodôntico Barra Palatina",
      "Aparelho Ortodôntico Bilmer",
      "Aparelho Ortodôntico Contenção",
      "Aparelho Ortodôntico Expansor",
      "Aparelho Ortodôntico Expansor com Mola",
      "Aparelho Ortodôntico Grade Palatina",
      "Aparelho Ortodôntico Hass",
      "Aparelho Ortodôntico Hyrax",
      "Aparelho Ortodôntico Mac Camera",
      "Estrutura Metálica de Prótese Parcial Removível PPR",
    ],
  },
];
