import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { FileText, Plus } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { PageHeader } from "@/components/page-header";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";

export const Route = createFileRoute("/_authenticated/prontuarios")({ component: Prontuarios });
type Person = { id: string; full_name: string };
type Note = { id: string; record_date: string; dentist_id: string | null; anamnesis: string | null; evolution: string; procedures: string | null; recommendations: string | null };

function Prontuarios() {
  const qc = useQueryClient(); const [patientId, setPatientId] = useState(""); const [open, setOpen] = useState(false); const [dentistId, setDentistId] = useState(""); const [anamnesis, setAnamnesis] = useState(""); const [evolution, setEvolution] = useState(""); const [procedures, setProcedures] = useState(""); const [recommendations, setRecommendations] = useState("");
  const { data: patients = [] } = useQuery({ queryKey: ["patients-mini"], queryFn: async () => { const { data, error } = await (supabase as any).from("patients").select("id, full_name").order("full_name"); if (error) throw error; return data as Person[]; } });
  const { data: dentists = [] } = useQuery({ queryKey: ["dentists-mini"], queryFn: async () => { const { data, error } = await supabase.from("dentists").select("id, full_name").order("full_name"); if (error) throw error; return data as Person[]; } });
  const { data: notes = [] } = useQuery({ queryKey: ["clinical-notes", patientId], enabled: !!patientId, queryFn: async () => { const { data, error } = await (supabase as any).from("clinical_notes").select("*").eq("patient_id", patientId).order("record_date", { ascending: false }); if (error) throw error; return data as Note[]; } });
  const reset = () => { setDentistId(""); setAnamnesis(""); setEvolution(""); setProcedures(""); setRecommendations(""); };
  const save = async (event: React.FormEvent) => { event.preventDefault(); if (!patientId || !evolution.trim()) return toast.error("Selecione o paciente e registre a evolução"); const { data: { user } } = await supabase.auth.getUser(); const { error } = await (supabase as any).from("clinical_notes").insert({ owner_id: user!.id, patient_id: patientId, dentist_id: dentistId || null, anamnesis: anamnesis.trim() || null, evolution: evolution.trim(), procedures: procedures.trim() || null, recommendations: recommendations.trim() || null }); if (error) return toast.error(error.message); toast.success("Registro salvo no prontuário"); setOpen(false); reset(); qc.invalidateQueries({ queryKey: ["clinical-notes", patientId] }); };
  const dentistName = (id: string | null) => dentists.find((dentist) => dentist.id === id)?.full_name ?? "Não informado";
  return <><PageHeader title="Prontuários" description="Histórico clínico, anamnese e evolução do paciente" actions={<Button disabled={!patientId} onClick={() => setOpen(true)}><Plus className="mr-1 h-4 w-4" /> Novo registro</Button>} /><Card className="mb-5"><CardContent className="max-w-lg p-4"><Label>Paciente</Label><Select value={patientId} onValueChange={setPatientId}><SelectTrigger className="mt-1.5"><SelectValue placeholder="Selecione o paciente para ver o prontuário" /></SelectTrigger><SelectContent>{patients.map((patient) => <SelectItem key={patient.id} value={patient.id}>{patient.full_name}</SelectItem>)}</SelectContent></Select></CardContent></Card>{!patientId ? <Card><CardContent className="py-16 text-center text-sm text-muted-foreground"><FileText className="mx-auto mb-3 h-7 w-7" />Selecione um paciente para acessar o prontuário.</CardContent></Card> : <div className="space-y-4">{notes.map((note) => <Card key={note.id}><CardContent className="space-y-3 p-5"><div className="flex justify-between gap-4"><div><p className="font-semibold">{new Date(`${note.record_date}T12:00:00`).toLocaleDateString("pt-BR")}</p><p className="text-xs text-muted-foreground">{dentistName(note.dentist_id)}</p></div></div>{note.anamnesis && <Section title="Anamnese" value={note.anamnesis} />}{note.evolution && <Section title="Evolução clínica" value={note.evolution} />}{note.procedures && <Section title="Procedimentos" value={note.procedures} />}{note.recommendations && <Section title="Orientações" value={note.recommendations} />}</CardContent></Card>)}{notes.length === 0 && <Card><CardContent className="py-12 text-center text-sm text-muted-foreground">Ainda não há registros para este paciente.</CardContent></Card>}</div>}<Dialog open={open} onOpenChange={(value) => { setOpen(value); if (!value) reset(); }}><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Novo registro clínico</DialogTitle></DialogHeader><form onSubmit={save} className="space-y-3"><div className="space-y-1.5"><Label>Dentista responsável</Label><Select value={dentistId} onValueChange={setDentistId}><SelectTrigger><SelectValue placeholder="Selecione" /></SelectTrigger><SelectContent>{dentists.map((dentist) => <SelectItem key={dentist.id} value={dentist.id}>{dentist.full_name}</SelectItem>)}</SelectContent></Select></div><Field label="Anamnese" value={anamnesis} onChange={setAnamnesis} /><Field label="Evolução clínica *" value={evolution} onChange={setEvolution} required /><Field label="Procedimentos realizados" value={procedures} onChange={setProcedures} /><Field label="Orientações ao paciente" value={recommendations} onChange={setRecommendations} /><DialogFooter><Button type="submit">Salvar no prontuário</Button></DialogFooter></form></DialogContent></Dialog></>;
}
function Field({ label, value, onChange, required = false }: { label: string; value: string; onChange: (value: string) => void; required?: boolean }) { return <div className="space-y-1.5"><Label>{label}</Label><Textarea required={required} value={value} onChange={(event) => onChange(event.target.value)} rows={3} /></div>; }
function Section({ title, value }: { title: string; value: string }) { return <div><p className="text-xs font-bold uppercase tracking-wide text-muted-foreground">{title}</p><p className="mt-1 whitespace-pre-wrap text-sm">{value}</p></div>; }
