/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedBoletinsRouteImport } from './routes/_authenticated/boletins'
import { Route as AuthenticatedCidadesRouteImport } from './routes/_authenticated/cidades'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDentistasRouteImport } from './routes/_authenticated/dentistas'
import { Route as AuthenticatedDespesasRouteImport } from './routes/_authenticated/despesas'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedFornecedoresRouteImport } from './routes/_authenticated/fornecedores'
import { Route as AuthenticatedOsRouteImport } from './routes/_authenticated/os'
import { Route as AuthenticatedPacientesRouteImport } from './routes/_authenticated/pacientes'
import { Route as AuthenticatedProteticosRouteImport } from './routes/_authenticated/proteticos'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedTiposAtendimentoRouteImport } from './routes/_authenticated/tipos-atendimento'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as ApiPublicReportPdfRouteImport } from './routes/api/public/report-pdf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBoletinsRoute = AuthenticatedBoletinsRouteImport.update({
  id: '/boletins',
  path: '/boletins',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCidadesRoute = AuthenticatedCidadesRouteImport.update({
  id: '/cidades',
  path: '/cidades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDentistasRoute = AuthenticatedDentistasRouteImport.update({
  id: '/dentistas',
  path: '/dentistas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDespesasRoute = AuthenticatedDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFornecedoresRoute =
  AuthenticatedFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOsRoute = AuthenticatedOsRouteImport.update({
  id: '/os',
  path: '/os',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPacientesRoute = AuthenticatedPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProteticosRoute = AuthenticatedProteticosRouteImport.update({
  id: '/proteticos',
  path: '/proteticos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTiposAtendimentoRoute =
  AuthenticatedTiposAtendimentoRouteImport.update({
    id: '/tipos-atendimento',
    path: '/tipos-atendimento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicReportPdfRoute = ApiPublicReportPdfRouteImport.update({
  id: '/api/public/report-pdf',
  path: '/api/public/report-pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/boletins': typeof AuthenticatedBoletinsRoute
  '/cidades': typeof AuthenticatedCidadesRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dentistas': typeof AuthenticatedDentistasRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/os': typeof AuthenticatedOsRoute
  '/pacientes': typeof AuthenticatedPacientesRoute
  '/proteticos': typeof AuthenticatedProteticosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/tipos-atendimento': typeof AuthenticatedTiposAtendimentoRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/public/report-pdf': typeof ApiPublicReportPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/boletins': typeof AuthenticatedBoletinsRoute
  '/cidades': typeof AuthenticatedCidadesRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dentistas': typeof AuthenticatedDentistasRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/os': typeof AuthenticatedOsRoute
  '/pacientes': typeof AuthenticatedPacientesRoute
  '/proteticos': typeof AuthenticatedProteticosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/tipos-atendimento': typeof AuthenticatedTiposAtendimentoRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/public/report-pdf': typeof ApiPublicReportPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/boletins': typeof AuthenticatedBoletinsRoute
  '/_authenticated/cidades': typeof AuthenticatedCidadesRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dentistas': typeof AuthenticatedDentistasRoute
  '/_authenticated/despesas': typeof AuthenticatedDespesasRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/_authenticated/os': typeof AuthenticatedOsRoute
  '/_authenticated/pacientes': typeof AuthenticatedPacientesRoute
  '/_authenticated/proteticos': typeof AuthenticatedProteticosRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/tipos-atendimento': typeof AuthenticatedTiposAtendimentoRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/api/public/report-pdf': typeof ApiPublicReportPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/boletins'
    | '/cidades'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/dentistas'
    | '/despesas'
    | '/financeiro'
    | '/fornecedores'
    | '/os'
    | '/pacientes'
    | '/proteticos'
    | '/relatorios'
    | '/tipos-atendimento'
    | '/usuarios'
    | '/api/public/report-pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/boletins'
    | '/cidades'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/dentistas'
    | '/despesas'
    | '/financeiro'
    | '/fornecedores'
    | '/os'
    | '/pacientes'
    | '/proteticos'
    | '/relatorios'
    | '/tipos-atendimento'
    | '/usuarios'
    | '/api/public/report-pdf'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/boletins'
    | '/_authenticated/cidades'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/dentistas'
    | '/_authenticated/despesas'
    | '/_authenticated/financeiro'
    | '/_authenticated/fornecedores'
    | '/_authenticated/os'
    | '/_authenticated/pacientes'
    | '/_authenticated/proteticos'
    | '/_authenticated/relatorios'
    | '/_authenticated/tipos-atendimento'
    | '/_authenticated/usuarios'
    | '/api/public/report-pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicReportPdfRoute: typeof ApiPublicReportPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/boletins': {
      id: '/_authenticated/boletins'
      path: '/boletins'
      fullPath: '/boletins'
      preLoaderRoute: typeof AuthenticatedBoletinsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cidades': {
      id: '/_authenticated/cidades'
      path: '/cidades'
      fullPath: '/cidades'
      preLoaderRoute: typeof AuthenticatedCidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dentistas': {
      id: '/_authenticated/dentistas'
      path: '/dentistas'
      fullPath: '/dentistas'
      preLoaderRoute: typeof AuthenticatedDentistasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/despesas': {
      id: '/_authenticated/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof AuthenticatedDespesasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fornecedores': {
      id: '/_authenticated/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AuthenticatedFornecedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/os': {
      id: '/_authenticated/os'
      path: '/os'
      fullPath: '/os'
      preLoaderRoute: typeof AuthenticatedOsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pacientes': {
      id: '/_authenticated/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof AuthenticatedPacientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/proteticos': {
      id: '/_authenticated/proteticos'
      path: '/proteticos'
      fullPath: '/proteticos'
      preLoaderRoute: typeof AuthenticatedProteticosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tipos-atendimento': {
      id: '/_authenticated/tipos-atendimento'
      path: '/tipos-atendimento'
      fullPath: '/tipos-atendimento'
      preLoaderRoute: typeof AuthenticatedTiposAtendimentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/report-pdf': {
      id: '/api/public/report-pdf'
      path: '/api/public/report-pdf'
      fullPath: '/api/public/report-pdf'
      preLoaderRoute: typeof ApiPublicReportPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBoletinsRoute: typeof AuthenticatedBoletinsRoute
  AuthenticatedCidadesRoute: typeof AuthenticatedCidadesRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDentistasRoute: typeof AuthenticatedDentistasRoute
  AuthenticatedDespesasRoute: typeof AuthenticatedDespesasRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedFornecedoresRoute: typeof AuthenticatedFornecedoresRoute
  AuthenticatedOsRoute: typeof AuthenticatedOsRoute
  AuthenticatedPacientesRoute: typeof AuthenticatedPacientesRoute
  AuthenticatedProteticosRoute: typeof AuthenticatedProteticosRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedTiposAtendimentoRoute: typeof AuthenticatedTiposAtendimentoRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBoletinsRoute: AuthenticatedBoletinsRoute,
  AuthenticatedCidadesRoute: AuthenticatedCidadesRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDentistasRoute: AuthenticatedDentistasRoute,
  AuthenticatedDespesasRoute: AuthenticatedDespesasRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedFornecedoresRoute: AuthenticatedFornecedoresRoute,
  AuthenticatedOsRoute: AuthenticatedOsRoute,
  AuthenticatedPacientesRoute: AuthenticatedPacientesRoute,
  AuthenticatedProteticosRoute: AuthenticatedProteticosRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedTiposAtendimentoRoute: AuthenticatedTiposAtendimentoRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicReportPdfRoute: ApiPublicReportPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
